apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustjack.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "rustjack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}